language: python
python:
  - 2.7

install:
  - pip install -r requirements_common.txt
  - pip install -r requirements_test.txt
  - cp project/settings/__init__.py.template project/settings/__init__.py
script:
  - ./manage.py test
after_success:
  coveralls

notifications:
  irc:
    channels:
      - "chat.freenode.net#one-love"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
  email:
    on_success: change
    on_failure: always
