language: python
python:
  - 2.7

script:
  - pip install -r requirements.txt
  - cp project/settings/__init__.py.template project/settings/__init__.py
  - python manage.py collectstatic --noinput

notifications:
  irc:
    channels:
      - "chat.freenode.net#one-love"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
  email:
    on_success: change
    on_failure: always
