language: python
python:
  - 2.7

script:
  - pip install -r requirements.txt
  - cp onelove/settings/__init__.py.template onelove/settings/__init__.py
  - python manage.py collectstatic

notifications:
  irc:
    channels:
      - "chat.freenode.net#one-love"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} %{message} %{build_url}"
  email:
    recipients:
      - meka@lugons.org
    on_success: change
    on_failure: always
